Refactor become_primary  scripts to resolve ShellCheck issues.

diff --git a/src/scripts/become_primary b/src/scripts/become_primary
--- a/src/scripts/become_primary
+++ b/src/scripts/become_primary
@@ -1,23 +1,34 @@
 #!/bin/bash
+
+# shellcheck source=/dev/null
+# Source the configuration file for iscsi-ha
 source /etc/iscsi-ha/iscsi-ha.load
+
+# Initialize retry counter
 RETRY=1
-if [ ! -e $IHA_STATE_PATH/manual ]
-then
-	echo "Host must be in manual mode for this operation"
-	echo "try 'iscsi-cfg manual-mode-enable'"
-	exit 1
+
+# Check if the host is in manual mode
+if [ ! -e "$IHA_STATE_PATH/manual" ]; then
+  echo "Host must be in manual mode for this operation."
+  echo "Try 'iscsi-cfg manual-mode-enable'."
+  exit 1
 fi
 
 echo "Waiting for peer to transition to secondary storage role"
-while :
-do
-	echo -ne "Attempt [$RETRY] to become primary storage role with infinite attempts\r"
-	/etc/iscsi-ha/scripts/iscsi-cfg become-primary &>/dev/null
-	RETVAL=$?
-	if [ $RETVAL -eq 0 ]
-	then
-		/etc/iscsi-ha/scripts/iscsi-cfg status && break
-	fi
-	RETRY=$(( $RETRY + 1 ))
-	sleep 1
+
+# Loop until the peer becomes the primary storage role
+while :; do
+  echo -ne "Attempt [$RETRY] to become primary storage role with infinite attempts\r"
+
+  # Attempt to become primary
+  if /etc/iscsi-ha/scripts/iscsi-cfg become-primary &>/dev/null; then
+    # Check the status and break the loop if successful
+    if /etc/iscsi-ha/scripts/iscsi-cfg status; then
+      break
+    fi
+  fi
+
+  # Increment the retry counter
+  RETRY=$((RETRY + 1))
+  sleep 1
 done
