Refactor get_replication_params to be more consistent with others similar functions.

diff --git a/src/usr/bin/iscsi-cfg-setup b/src/usr/bin/iscsi-cfg-setup
--- a/src/usr/bin/iscsi-cfg-setup
+++ b/src/usr/bin/iscsi-cfg-setup
@@ -421,38 +421,51 @@ get_replication_params() {
   REPLICATION_SUBNET=$(awk -F. '{print $1"."$2"."$3".0/24"}' <<<"$REPLICATION_IP_ISCSI")
   echo "Replication subnet determined: $REPLICATION_SUBNET"
 
-  # Display all network interfaces with 'xapi' or 'xenbr'
-  echo "The following interfaces were found on this host:"
-  ip addr show | grep 'inet' | grep -E 'xapi|xenbr'
-  echo
-  echo "Select replication interface:"
+  clear
+  while :; do
+    # Display all network interfaces with 'xapi' or 'xenbr'
+    echo "The following interfaces were found on this host:"
+    ip addr show | grep 'inet' | grep -E 'xenbr|xapi'
+    echo
+    echo "Select replication interface:"
 
-  # Retrieve and store all available interfaces in an array
-  mapfile -t IF_LIST < <(ip addr show | grep -E 'xenbr|xapi' | grep : | awk -F ": " '{print $2}')
+    # Retrieve and store all available interfaces in an array
+    mapfile -t replication_dev_list < <(ip addr show | grep -E 'xenbr|xapi' | grep : | awk -F ": " '{print $2}')
 
-  # Exit if no suitable interfaces are found
-  if [ ${#IF_LIST[@]} -eq 0 ]; then
-    echo "No suitable interfaces found. Exiting..."
-    exit 1
-  fi
+    # Exit if no suitable interfaces are found
+    if [[ ${#replication_dev_list[@]} -eq 0 ]]; then
+      echo "No suitable interfaces found. Exiting..."
+      exit 1
+    fi
 
-  # Display each interface with a numeric option for selection
-  for i in "${!IF_LIST[@]}"; do
-    echo "Enter $i for interface ${IF_LIST[$i]}"
+    # If REPLICATION_DEV_NAME is already set, add it to the list in green
+    if [ -n "$REPLICATION_DEV_NAME" ]; then
+      replication_dev_list=("$REPLICATION_DEV_NAME" "${replication_dev_list[@]}")
+    fi
+
+    # Display each interface with a numeric option for selection
+    for i in "${!replication_dev_list[@]}"; do
+      if [[ "$i" -eq 0 && -n "$REPLICATION_DEV_NAME" ]]; then
+        # Apply color and custom text to the current user's replication interface
+        echo "[$((i + 1))]  $(set_color "green")${replication_dev_list[$i]} (current used)$(set_color "normal")"
+      else
+        echo "[$((i + 1))] ${replication_dev_list[$i]}"
+      fi
+    done
+
+    # Prompt the user to select an interface
+    read -r -p "Enter choice (1-${#replication_dev_list[@]} for the Replication Interface :" replication_dev_index
+
+    # Validate the user's selection and set the replication device name
+    if [[ $replication_dev_index =~ ^[0-9]+$ && "$replication_dev_index" -ge 1 && "$replication_dev_index" -le ${#replication_dev_list[@]} ]]; then
+      REPLICATION_DEV_NAME=${replication_dev_list[$((replication_dev_index - 1))]}
+      echo "Selected Replication Interface: $REPLICATION_DEV_NAME"
+      break
+    else
+      clear
+      echo "Invalid selection [$replication_dev_index]. Please choose between 1 and ${#replication_dev_list[@]}."
+    fi
   done
-
-  # Prompt the user to select an interface
-  echo "Enter 0 - $((${#IF_LIST[@]} - 1)) for the desired Replication Interface:"
-  read -r SELECT_REPLICATION_DEV_NAME
-
-  # Validate the user's selection and set the replication device name
-  if [[ $SELECT_REPLICATION_DEV_NAME =~ ^[0-9]+$ ]] && [ "$SELECT_REPLICATION_DEV_NAME" -ge 0 ] && [ "$SELECT_REPLICATION_DEV_NAME" -lt ${#IF_LIST[@]} ]; then
-    REPLICATION_DEV_NAME=${IF_LIST[$SELECT_REPLICATION_DEV_NAME]}
-    echo "Interface $REPLICATION_DEV_NAME selected"
-  else
-    echo "Invalid selection. Exiting..."
-    exit 1
-  fi
 }
 
 # Function to handle the process of selecting a block device
@@ -631,6 +644,7 @@ $(set_color "yellow")Replication Block Device: $BLOCK_DEVICE $(set_color "normal
 # rollback is required:
 #   THIS_HOST_LOCAL_STORAGE_PBD_DEVICE
 ########################################
+# TODO: we should remove local storage in both servers
 remove_local_storage() {
   # Get the local storage SR UUID for the host
   this_host_local_storage=$(xe sr-list type=lvm host="$(hostname)" --minimal)
@@ -878,7 +892,6 @@ firewall_update() {
   echo "Adding firewall rules to allow traffic between hosts on the replication subnet."
 
   # Check if the REPLICATION_SUBNET is defined and not empty
-  # TODO: use values from user local conf
   if [ -z "$REPLICATION_SUBNET" ]; then
     echo "Error: REPLICATION_SUBNET is not set."
     exit 1
@@ -1036,7 +1049,7 @@ drbd_get_link_speed() {
 
     # Display the list of options
     for i in "${!link_speed_list[@]}"; do
-      if [ "$i" -eq 0 ] && [ -n "$LINK_SPEED_BYTES" ]; then
+      if [[ "$i" -eq 0 && -n "$LINK_SPEED_BYTES" ]]; then
         # Apply color and custom text to the current user's link speed
         echo "[$((i + 1))]  $(set_color "green")$((link_speed_list[i] / 1000000)) Mbps (current used speed)$(set_color "normal")"
       else
@@ -1066,9 +1079,15 @@ drbd_get_link_speed() {
 # (ranging from 100MiB/s to 1000MiB/s or greater) and asks the user to select a
 # speed by entering the corresponding number. The selected speed is stored in
 # the variable $DISK_SPEED.
+#
+# If DISK_SPEED is set on user local config, add it as the first option in the list.
+#
+# The function will display the selected speed in MiB/s and store it in DISK_SPEED.
 drbd_get_disk_throughput() {
+  local -a disk_speed_list
+
   # Predefined disk throughput options in bytes per second (Bps)
-  declare -a disk_speed_list=(
+  disk_speed_list=(
     104857600  # 100MiB/s
     157286400  # 150MiB/s
     209715200  # 200MiB/s
@@ -1084,7 +1103,7 @@ drbd_get_disk_throughput() {
   )
 
   # If DISK_SPEED is set on user local config, add it as the first option
-  if [ -n "$DISK_SPEED" ]; then
+  if [[ -n "$DISK_SPEED" ]]; then
     disk_speed_list=("$DISK_SPEED" "${disk_speed_list[@]}")
   fi
 
@@ -1095,7 +1114,7 @@ drbd_get_disk_throughput() {
 
     # Display the list of options
     for i in "${!disk_speed_list[@]}"; do
-      if [ "$i" -eq 0 ] && [ -n "$DISK_SPEED" ]; then
+      if [[ "$i" -eq 0 && -n "$DISK_SPEED" ]]; then
         # Apply color and custom text to the current user's disk speed
         echo "[$((i + 1))]  $(set_color "green")$((disk_speed_list[i] / 1048576)) MiB/s (current used speed)$(set_color "normal")"
       else
@@ -1104,17 +1123,11 @@ drbd_get_disk_throughput() {
       fi
     done
 
-    read -r -p "Enter choice (1-${#disk_speed_list[@]}): " disk_speed_index
-
-    if [[ "$disk_speed_index" -ge 1 && "$disk_speed_index" -le ${#disk_speed_list[@]} ]]; then
-      # Use the selected speed from the list
-      selected_speed=${disk_speed_list[$((disk_speed_index - 1))]}
-
-      # If the selected option is a numeric speed value, update DISK_SPEED
-      if [[ "$selected_speed" =~ ^[0-9]+$ ]]; then
-        DISK_SPEED=$selected_speed
-        echo "Selected disk throughput: $((DISK_SPEED / 1048576)) MiB/s"
-      fi
+    read -r -p "Enter choice (1-${#disk_speed_list[@]}) for Disk Speed : " disk_speed_index
+    # Validate if the user input is a number between 1 and ${#disk_speed_list[@]}
+    if [[ "$disk_speed_index" =~ ^[0-9]+$ && "$disk_speed_index" -ge 1 && "$disk_speed_index" -le ${#disk_speed_list[@]} ]]; then
+      DISK_SPEED=${disk_speed_list[$((disk_speed_index - 1))]}
+      echo "Selected disk throughput: $((DISK_SPEED / 1048576)) MiB/s"
       break
     else
       clear
@@ -1515,7 +1528,6 @@ else
   # Display welcome message and check if required commands are available
   check_welcome
 
-  # TODO: check if services are stopped (running the setup again)
   # Verify that all required commands are installed
   check_required_commands
   # Check the host role within the pool (e.g., master or slave)
@@ -1563,6 +1575,7 @@ else
     exit 0
   fi
 
+  # TODO: check if services are stopped (running the setup again)
   # Step 4: Apply system changes
   # Now that all checks and validations are done, we start applying configuration changes
   # Update firewall rules to allow necessary traffic
