Refactor watchdog init proccess to manager change of pid.

diff --git a/src/etc/init.d/iscsi-ha-watchdog b/src/etc/init.d/iscsi-ha-watchdog
--- a/src/etc/init.d/iscsi-ha-watchdog
+++ b/src/etc/init.d/iscsi-ha-watchdog
@@ -35,7 +35,7 @@ check_process_status() {
 
     case "$RETVAL" in
     0)
-      log "$PROCESS_NAME Watchdog: $PROCESS_NAME running - OK"
+      log "${PROCESS_NAME} Watchdog: ${PROCESS_NAME} running - OK"
       ;;
     1)
       log "${PROCESS_NAME} Watchdog: ${PROCESS_NAME} is dead but pid file exists, starting ${PROCESS_NAME}"
@@ -50,6 +50,25 @@ check_process_status() {
       /etc/init.d/"${PROCESS_NAME}" start
       ;;
     esac
+
+    local bg_pid=$?
+
+    # Check if the background process was started successfully
+    if [[ $bg_pid -eq 0 ]]; then
+      touch "${LOCK_FILE}"
+      touch "${PID_FILE}"
+      pidof -x "${PROC_NAME}" >"${PID_FILE}"
+      echo "Starting ${PROC_NAME}: "
+      success
+    else
+      failure "${PROC_NAME} startup failed"
+      echo "Failed to start ${PROC_NAME}"
+      killproc "${PROC_NAME}" 2>/dev/null
+      rm -f "${LOCK_FILE}" "${PID_FILE}"
+      exit 1
+    fi
+    echo
+
   done
 }
 
@@ -63,7 +82,6 @@ start_watchdog() {
 
     # Iterate over each PID in the file
     while read -r pid; do
-      echo "Processing PID: ${pid}"
       if kill -0 "${pid}" 2>/dev/null; then
         failure "${PROC_NAME} already running: ${pid} startup failed"
         echo "${PROC_NAME} already running: ${pid} startup failed"
@@ -74,25 +92,7 @@ start_watchdog() {
 
   # Start the check_process_status function in the background
   check_process_status &
-  local bg_pid=$?
-
-  # Check if the background process was started successfully
-  if [[ $bg_pid -eq 0 ]]; then
-    touch "${LOCK_FILE}"
-    touch "${PID_FILE}"
-    pidof -x "${PROC_NAME}" >"${PID_FILE}"
-    echo -n "Starting ${PROC_NAME}: "
-    success
-  else
-    failure "${PROC_NAME} startup failed"
-    echo "Failed to start ${PROC_NAME}"
-    killproc "${PROC_NAME}" 2>/dev/null
-    rm -f "${LOCK_FILE}" "${PID_FILE}"
-    exit 1
-  fi
-  echo
 }
-
 #########################################
 # Description: Stop the watchdog process.
 #########################################
