Refactor init scripts to resolve ShellCheck issues.

diff --git a/src/init/iscsi-ha-watchdog b/src/init/iscsi-ha-watchdog
--- a/src/init/iscsi-ha-watchdog
+++ b/src/init/iscsi-ha-watchdog
@@ -1,156 +1,162 @@
 #!/bin/bash
 #
-# 
 # chkconfig: 2345 99 01
-# description: iscsi-ha watchdog script
+# description: iscsi-ha-watchdog script version __VERSION__
 # processname: iscsi-ha-watchdog
 
-# Function library
+# shellcheck source=/dev/null
+
+# Load function library
 . /etc/init.d/functions
 
-VERSION="2.1"
+# Define constants
 WATCH_INTERVAL="5"
 PROCESS_NAME="iscsi-ha"
-PROC_NAME=${PROCESS_NAME}-watchdog
-PID_FILE=/var/run/${PROC_NAME}.pid
-LOCK_FILE=/var/lock/subsys/${PROC_NAME}
-GLOBAL_CONF=/etc/iscsi-ha/iscsi-ha.load
-OVERIDE_CONF=/etc/iscsi-ha/iscsi-ha.conf
-LIB_FUNCTIONS=/etc/iscsi-ha/iscsi-ha.func
+PROC_NAME="${PROCESS_NAME}-watchdog"
+PID_FILE="/var/run/${PROC_NAME}.pid"
+LOCK_FILE="/var/lock/subsys/${PROC_NAME}"
+GLOBAL_CONF="/etc/iscsi-ha/iscsi-ha.load"
+OVERRIDE_CONF="/etc/iscsi-ha/iscsi-ha.conf"
+LIB_FUNCTIONS="/usr/lib64/iscsi-ha/iscsi-ha.func"
 
-check () {
-	source ${LIB_FUNCTIONS}
-	source ${GLOBAL_CONF}
-	source ${OVERIDE_CONF}
+# Load necessary configuration files
+source "$LIB_FUNCTIONS"
+source "$GLOBAL_CONF"
+source "$OVERRIDE_CONF"
 
+#########################################
+# Description: Monitor the iscsi-ha service and take appropriate actions
+#########################################
+check_process_status() {
+  while true; do
+    sleep "$WATCH_INTERVAL"
+    status "$PROCESS_NAME" &>/dev/null
+    local RETVAL=$?
 
-	while :
-	do
-		sleep $WATCH_INTERVAL
-		status $PROCESS_NAME &> /dev/null 
-		RETVAL=$?
-		case $RETVAL in
-		
-		0)
-			log "$PROCESS_NAME Watchdog: $PROCESS_NAME running - OK "
-			;;
-		1)	
-			log "$PROCESS_NAME Watchdog: $PROCESS_NAME is dead but pid file exists, starting $PROCESS_NAME"
-			/etc/init.d/$PROCESS_NAME start #service $PROCESS_NAME start 
-	                ;;
-		2)
-			log "$PROCESS_NAME Watchdog: $PROCESS_NAME is dead but subsys locked, starting $PROCESS_NAME"
-	                /etc/init.d/$PROCESS_NAME start #service $PROCESS_NAME start
-	                ;;
-		3)
-			log "$PROCESS_NAME Watchdog: $PROCESS_NAME is stopped, starting $PROCESS_NAME"
-	                /etc/init.d/$PROCESS_NAME start #service $PROCESS_NAME start
-	                ;;
-		esac
-	done
+    case "$RETVAL" in
+    0)
+      log "$PROCESS_NAME Watchdog: $PROCESS_NAME running - OK"
+      ;;
+    1)
+      log "${PROCESS_NAME} Watchdog: ${PROCESS_NAME} is dead but pid file exists, starting ${PROCESS_NAME}"
+      /etc/init.d/"${PROCESS_NAME}" start
+      ;;
+    2)
+      log "${PROCESS_NAME} Watchdog: ${PROCESS_NAME} is dead but subsys locked, starting ${PROCESS_NAME}"
+      /etc/init.d/"${PROCESS_NAME}" start
+      ;;
+    3)
+      log "${PROCESS_NAME} Watchdog: ${PROCESS_NAME} is stopped, starting ${PROCESS_NAME}"
+      /etc/init.d/"${PROCESS_NAME}" start
+      ;;
+    esac
+  done
 }
 
-start() {
-        if  [ -e $PID_FILE ]
-        then
-                for i in `/bin/cat $PID_FILE` # This can be an array
-                do
-			kill -0 $i 2> /dev/null
-			RETVAL=$?
-                        if [ $RETVAL -eq 0 ]
-			then
-				failure $"$PROC_NAME already running: $CURRENT_PID startup failed"
-				echo $"$PROC_NAME already running: $CURRENT_PID startup failed"
-				exit 1
-			fi
-                done
+#########################################
+# Description: Start the watchdog process.
+#########################################
+start_watchdog() {
+  # Check if the watchdog process is already running
+  if [[ -e "${PID_FILE}" ]]; then
+    # Read each line (PID) from the PID file
+    while read -r pid; do
+      kill -0 "${pid}" 2>/dev/null
+      RETVAL=$?
+      if [[ ${RETVAL} -eq 0 ]]; then
+        failure "${PROC_NAME} already running: ${pid} startup failed"
+        echo "${PROC_NAME} already running: ${pid} startup failed"
+        exit 1
+      fi
+    done <"${PID_FILE}" # Redirect PID_FILE to the while loop
+  fi
+
+  # Start the watchdog process
+  if check_process_status; then
+    touch "${LOCK_FILE}"
+    touch "${PID_FILE}"
+    pidof -x "${PROC_NAME}" >"${PID_FILE}"
+    echo -n "Starting ${PROC_NAME}: "
+    success
+  else
+    failure "${PROC_NAME} startup failed"
+    echo "Failed to start ${PROC_NAME}"
+    killproc "${PROC_NAME}" 2>/dev/null
+    rm -f "${LOCK_FILE}" "${PID_FILE}"
+    exit 1
+  fi
+  echo
+}
+
+#########################################
+# Description: Stop the watchdog process.
+#########################################
+stop_watchdog() {
+  echo -n "Stopping ${PROC_NAME}: "
+  killproc "${PROC_NAME}" 2>/dev/null
+  RETVAL=$?
+
+  if [[ ${RETVAL} -eq 0 ]]; then
+    rm -f "${LOCK_FILE}" "${PID_FILE}"
+    success "${PROC_NAME} stopped"
+  else
+    warning "Failed to stop ${PROC_NAME}"
+    echo "Error stopping ${PROC_NAME}"
+    exit 1
+  fi
+  echo
+}
+
+#########################################
+# Description: Check the status of the watchdog process.
+#########################################
+check_watchdog_status() {
+  if [[ -e "${PID_FILE}" ]]; then
+    if [[ -e "${PID_FILE}" ]]; then
+      # Read each line (PID) from the PID file
+      while read -r pid; do
+        kill -0 "${pid}" 2>/dev/null
+        RETVAL=$?
+        if [[ ${RETVAL} -eq 0 ]]; then
+          success "${PROC_NAME} running: ${pid}"
+          echo "${PROC_NAME} running: ${pid}"
+          exit 0
         fi
+      done <"${PID_FILE}" # Redirect PID_FILE to the while loop
+    fi
 
-        check &
-        if [ $? = 0 ]
-        then
-                /bin/touch $LOCK_FILE 
-                /bin/touch $PID_FILE
-                echo `pidof -x $PROC_NAME` > $PID_FILE
-                echo -n $"Starting $PROC_NAME: "
-                success
-        else
-                failure $"$PROC_NAME startup"
-                echo $"Failed to start $PROC_NAME"
-                killproc $PROC_NAME 2>/dev/null
-                rm -f $LOCK_FILE 
-                rm -f $PIDFILE
-                exit 1
-        fi
-        echo
+    warning "${PROC_NAME} is dead and ${PID_FILE} exists"
+    echo "${PROC_NAME} is dead and ${PID_FILE} exists"
+    exit 1
+  elif [[ -e "${LOCK_FILE}" ]]; then
+    warning "${PROC_NAME} is dead and ${LOCK_FILE} exists"
+    echo "${PROC_NAME} is dead and ${LOCK_FILE} exists"
+    exit 2
+  else
+    failure "${PROC_NAME} is not running"
+    echo "${PROC_NAME} is not running"
+    exit 3
+  fi
 }
 
-stop() {
-        echo -n $"Stopping $PROC_NAME: "
-	killproc $PROC_NAME 2>/dev/null
-	RETVAL=$?
-	if [ $RETVAL = 0 ]
-	then
-		success $"$PROC_NAME stop"
-		rm -f $LOCK_FILE 
-		rm -f $PID_FILE
-	else
-		warning $"$PROC_NAME stop"
-        	echo $"Error stopping $PROC_NAME"
-		exit 1
-	fi
-	echo
-}
-
-this_status () {
-	if  [ -e $PID_FILE ]
-	then
-		for i in `/bin/cat $PID_FILE` # This can be an array
-		do
-			kill -0 $i 2> /dev/null
-			RETVAL=$?
-			if [ $RETVAL -eq 0 ]
-			then
-				success $"$PROC_NAME running: $i"
-				echo $"$PROC_NAME running: $i"
-				exit 0
-			fi
-		done
-
-		warning $"$PROC_NAME is dead and /var/run pid file exists"
-		echo "$PROC_NAME is dead and /var/run pid file exists"
-		exit 1
-	elif [ -e $LOCK_FILE ]
-	then
-		warning $"$PROC_NAME is dead and /var/lock lock file exists"
-		echo "$PROC_NAME is dead and /var/lock lock file exists"
-		exit 2
-	else
-		failure $"$PROC_NAME is not running"
-		echo "$PROC_NAME is not running"
-		exit 3
-	fi
-
-} #End status
-
-
+# Main control flow based on input argument
 case "$1" in
-	start)
-        	start
-        	;;
-	stop)
-        	stop
-        	;;
-	status)
-		this_status
-        	;;
-	restart)
-		stop
-		start
-		;;
-	 *)
-        	echo $"Usage: $0 {start|stop|restart|status}"
-        	exit 1
-		;;
+start)
+  start_watchdog
+  ;;
+stop)
+  stop_watchdog
+  ;;
+status)
+  check_watchdog_status
+  ;;
+restart)
+  stop_watchdog
+  start_watchdog
+  ;;
+*)
+  echo "Usage: $0 {start|stop|restart|status}"
+  exit 1
+  ;;
 esac
 exit 0
